services:
  postgres:
    image: postgres:16-alpine
    container_name: kubi-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kubi
      POSTGRES_USER: kubi
      POSTGRES_PASSWORD: kubi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kubi"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres-data:
    driver: local
